name: CI
on: [push]
jobs:
  google-test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Set up test env
        run: |
            sudo apt update
            sudo apt install cmake g++ make
      - name: Init codeql
        uses: github/codeql-action/init@v4
        with:
          languages: cpp
          queries: security-and-quality
      - name: Build solution
        run: cmake -S . -B ./build && cmake --build ./build
      - name: Run tests
        run: ctest --test-dir ./build
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4